services:
  astro-blog:
    build: .
    container_name: astro-blog
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro.rule=Host(`bigouden.org`)"
      - "traefik.http.routers.astro.entrypoints=https"
      - "traefik.http.routers.astro.tls=true"
      # Middleware to redirect www to non-www
      - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.regex=^https?://www\\.(.*)"
      - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.replacement=https://$$1"
      - "traefik.http.routers.www-astro.rule=Host(`www.bigouden.org`)"
      - "traefik.http.routers.www-astro.entrypoints=https"
      - "traefik.http.routers.www-astro.middlewares=redirect-www-to-non-www"
      - "traefik.http.routers.www-astro.tls=true"
    networks:
      - proxy

networks:
  proxy:
    external: true

